/**
 * Canonical topic/tag list used across all platforms.
 * Platform-specific tags are normalised to these slugs by the mappers.
 */
export const TOPICS = [
  "arrays",
  "strings",
  "hash-tables",
  "sorting",
  "binary-search",
  "two-pointers",
  "sliding-window",
  "prefix-sum",
  "greedy",
  "recursion",
  "dynamic-programming",
  "memoization",
  "bitmask-dp",
  "tree-dp",
  "graphs",
  "bfs",
  "dfs",
  "shortest-path",
  "minimum-spanning-tree",
  "topological-sort",
  "trees",
  "binary-trees",
  "binary-search-trees",
  "segment-trees",
  "fenwick-trees",
  "heaps",
  "stacks",
  "queues",
  "linked-lists",
  "tries",
  "union-find",
  "number-theory",
  "prime-sieve",
  "combinatorics",
  "probability",
  "geometry",
  "constructive",
  "implementation",
  "simulation",
  "brute-force",
  "divide-and-conquer",
  "backtracking",
  "game-theory",
  "interactive",
  "data-structures",
] as const;

export type Topic = (typeof TOPICS)[number];

/** Topics typically taught first — used to prioritise recommendations for beginners. */
export const BEGINNER_TOPICS: Topic[] = [
  "arrays",
  "strings",
  "sorting",
  "hash-tables",
  "two-pointers",
  "prefix-sum",
  "binary-search",
  "recursion",
  "greedy",
  "implementation",
];

/** Topics considered advanced — higher skill-score threshold needed. */
export const ADVANCED_TOPICS: Topic[] = [
  "dynamic-programming",
  "bitmask-dp",
  "tree-dp",
  "segment-trees",
  "minimum-spanning-tree",
  "topological-sort",
  "number-theory",
  "combinatorics",
  "game-theory",
  "geometry",
];

/**
 * Maps raw Codeforces/LeetCode/AtCoder tag strings → canonical Topic slug.
 * Unmapped tags are dropped (not stored as topic stats).
 */
export const TAG_NORMALISATION_MAP: Record<string, Topic> = {
  // Codeforces tags
  "dp": "dynamic-programming",
  "dynamic programming": "dynamic-programming",
  "graphs": "graphs",
  "graph": "graphs",
  "trees": "trees",
  "tree": "trees",
  "greedy": "greedy",
  "binary search": "binary-search",
  "bfs": "bfs",
  "dfs": "dfs",
  "sortings": "sorting",
  "sorting": "sorting",
  "strings": "strings",
  "string": "strings",
  "number theory": "number-theory",
  "combinatorics": "combinatorics",
  "implementation": "implementation",
  "constructive algorithms": "constructive",
  "data structures": "data-structures",
  "two pointers": "two-pointers",
  "divide and conquer": "divide-and-conquer",
  "backtracking": "backtracking",
  "brute force": "brute-force",
  "bitmasks": "bitmask-dp",
  "geometry": "geometry",
  "game theory": "game-theory",
  "hashing": "hash-tables",
  "shortest paths": "shortest-path",
  "minimum spanning tree": "minimum-spanning-tree",
  "segment tree": "segment-trees",
  "fenwick tree": "fenwick-trees",
  "dsu": "union-find",
  "union find": "union-find",
  "topological sort": "topological-sort",
  "probabilities": "probability",
  "interactive": "interactive",
  "simulation": "simulation",
  "trie": "tries",
  // LeetCode tags
  "array": "arrays",
  "hash table": "hash-tables",
  "linked list": "linked-lists",
  "math": "number-theory",
  "depth-first search": "dfs",
  "breadth-first search": "bfs",
  "heap (priority queue)": "heaps",
  "prefix sum": "prefix-sum",
  "sliding window": "sliding-window",
  "monotonic stack": "stacks",
  "stack": "stacks",
  "queue": "queues",
  "union find": "union-find",
  "segment tree": "segment-trees",
  "binary indexed tree": "fenwick-trees",
  "divide and conquer": "divide-and-conquer",
  "memoization": "memoization",
  "bit manipulation": "bitmask-dp",
  "recursion": "recursion",
  "backtracking": "backtracking",
  "binary search": "binary-search",
  "binary search tree": "binary-search-trees",
  "binary tree": "binary-trees",
  "tree": "trees",
  "graph": "graphs",
  "topological sort": "topological-sort",
  "shortest path": "shortest-path",
  "trie": "tries",
  "geometry": "geometry",
  "game theory": "game-theory",
  "greedy": "greedy",
  "simulation": "simulation",
  "counting": "combinatorics",
};
